version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://production-review-tool.herokuapp.com/api/buildNotification
jobs:
  build:
    docker:
     - image: circleci/android:api-25-alpha
    working_directory: ~/mhsystems_android
    steps:
      - checkout
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew
      - run:
            name: Check Rejected Commits
            command: ./deploy
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies


