#!/bin/bash
content=$(wget https://production-review-tool.herokuapp.com/api/checkReadyToDeploy?app_name=mhsystems_android -q -O -)

echo $content
if [ "${content:1:14}" == '"success":true' ]; then 
 exit 0
fi
exit 1
